### ISSUE TITLE
[Flatpak] Cannot build ElmerGUI. bin/ld: cannot find -lMPI::MPI_C

### ISSUE THREAD

**Issue by kevinsmia1939** [ElmerCSC/elmerfem#292] opened 2021-10-13 10:12 UTC
Hello, I am packaging ElmerGUI as Flatpak on openSUSE Tumbleweed Linux.
I encounter an error when building ElmerGUI.
```
[ 65%] Building Fortran object fem/src/CMakeFiles/elmersolver.dir/TimeIntegrate.F90.o
[ 65%] Building Fortran object fem/src/CMakeFiles/elmersolver.dir/ListMatrix.F90.o
[ 65%] Building Fortran object fem/src/CMakeFiles/elmersolver.dir/IterativeMethods.F90.o
[ 65%] Linking CXX executable ElmerGUI
[ 65%] Building Fortran object fem/src/CMakeFiles/elmersolver.dir/IterSolve.F90.o
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lMPI::MPI_C
[ 65%] Building Fortran object fem/src/CMakeFiles/elmersolver.dir/SParIterSolver.F90.o
collect2: error: ld returned 1 exit status
make[2]: *** [ElmerGUI/Application/CMakeFiles/ElmerGUI.dir/build.make:1352: ElmerGUI/Application/ElmerGUI] Error 1
make[1]: *** [CMakeFiles/Makefile2:24531: ElmerGUI/Application/CMakeFiles/ElmerGUI.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
This is how I build ElmerGUI
In the flatpak manifest file, I add -Ldir to try to tell ld to search inside /app/lib, but no progress.
```
      cflags: -L/app/lib
      cxxflags: -L/app/lib

      - -DCMAKE_BUILD_TYPE:STRING=Release
      - -DWITH_ELMERGUI:BOOL=TRUE
      - -DWITH_ELMERGUILOGGER:BOOL=TRUE
      - -DWITH_CONTRIB=ON
      - -DWITH_OpenMP:BOOL=TRUE
      - -DWITH_MPI:BOOL=TRUE
      - -DWITH_Mumps:BOOL=TRUE
      - -DWITH_Hypre:BOOL=TRUE
      - -DWITH_ScatteredDataInterpolator=ON
      - -DWITH_ElmerIce:BOOL=TRUE
      - -DMumps_INCLUDE_DIR=/app/include
      - -DMumps_LIBRARIES=/app/lib
      - -DWITH_QT5=TRUE
      - -DWITH_VTK=ON
```

For Open MPI, I only have this enabled.
```
      - --enable-mpi-fortran
      - --enable-mpi-cxx
```
flatpak-builder 1.0.14

I don't understand what is " -lMPI::MPI_C". I only understand -lMPI which ld look for libMPI.so etc. But I don't know the "::MPI_C" part.

For Flatpak, when buildling dependencies, the installed prefix will be at `/app`.
Which I have libmpi.so... in /app/lib/.
```
Running: ln -s /app/lib/libmpi.so /app/lib/libMPI.so
Running: ls -l /app/lib/ | grep -i libmpi.*
-rwxr-xr-x 2 kev users     1083 Jan  1  1970 libmpi_cxx.la
lrwxrwxrwx 1 kev users       21 Oct 13 12:03 libmpi_cxx.so -> libmpi_cxx.so.40.30.0
lrwxrwxrwx 1 kev users       21 Oct 13 12:03 libmpi_cxx.so.40 -> libmpi_cxx.so.40.30.0
-rwxr-xr-x 2 kev users   121120 Jan  1  1970 libmpi_cxx.so.40.30.0
-rwxr-xr-x 2 kev users     1044 Jan  1  1970 libmpi.la
-rwxr-xr-x 2 kev users     1099 Jan  1  1970 libmpi_mpifh.la
lrwxrwxrwx 1 kev users       23 Oct 13 12:03 libmpi_mpifh.so -> libmpi_mpifh.so.40.30.0
lrwxrwxrwx 1 kev users       23 Oct 13 12:03 libmpi_mpifh.so.40 -> libmpi_mpifh.so.40.30.0
-rwxr-xr-x 2 kev users   464928 Jan  1  1970 libmpi_mpifh.so.40.30.0
lrwxrwxrwx 1 kev users       17 Oct 13 12:03 libmpi.so -> libmpi.so.40.30.1
lrwxrwxrwx 1 kev users       18 Oct 13 12:03 libMPI.so -> /app/lib/libmpi.so
lrwxrwxrwx 1 kev users       17 Oct 13 12:03 libmpi.so.40 -> libmpi.so.40.30.1
-rwxr-xr-x 2 kev users  1113976 Jan  1  1970 libmpi.so.40.30.1
-rwxr-xr-x 2 kev users     1144 Jan  1  1970 libmpi_usempif08.la
lrwxrwxrwx 1 kev users       27 Oct 13 12:03 libmpi_usempif08.so -> libmpi_usempif08.so.40.30.0
lrwxrwxrwx 1 kev users       27 Oct 13 12:03 libmpi_usempif08.so.40 -> libmpi_usempif08.so.40.30.0
-rwxr-xr-x 2 kev users   297952 Jan  1  1970 libmpi_usempif08.so.40.30.0
-rwxr-xr-x 2 kev users     1093 Jan  1  1970 libmpi_usempi_ignore_tkr.la
lrwxrwxrwx 1 kev users       35 Oct 13 12:03 libmpi_usempi_ignore_tkr.so -> libmpi_usempi_ignore_tkr.so.40.30.0
lrwxrwxrwx 1 kev users       35 Oct 13 12:03 libmpi_usempi_ignore_tkr.so.40 -> libmpi_usempi_ignore_tkr.so.40.30.0
-rwxr-xr-x 2 kev users    59152 Jan  1  1970 libmpi_usempi_ignore_tkr.so.40.30.0
```

But running `ld -lMPI --verbose` show that it is looking in `/usr/lib`.
```
ld: mode elf_x86_64
attempt to open /usr/x86_64-unknown-linux-gnu/lib64/libMPI.so failed
attempt to open /usr/x86_64-unknown-linux-gnu/lib64/libMPI.a failed
attempt to open /usr/lib/x86_64-linux-gnu/libMPI.so failed
attempt to open /usr/lib/x86_64-linux-gnu/libMPI.a failed
attempt to open /usr/lib/libMPI.so failed
attempt to open /usr/lib/libMPI.a failed
attempt to open /usr/x86_64-unknown-linux-gnu/lib/libMPI.so failed
attempt to open /usr/x86_64-unknown-linux-gnu/lib/libMPI.a failed
ld: cannot find -lMPI
attempt to open /usr/x86_64-unknown-linux-gnu/lib64/libMPI.so failed
attempt to open /usr/x86_64-unknown-linux-gnu/lib64/MPI.a failed
attempt to open /usr/lib/x86_64-linux-gnu/libMPI.so failed
attempt to open /usr/lib/x86_64-linux-gnu/MPI.a failed
attempt to open /usr/lib/libMPI.so failed
attempt to open /usr/lib/MPI.a failed
attempt to open /usr/x86_64-unknown-linux-gnu/lib/libMPI.so failed
attempt to open /usr/x86_64-unknown-linux-gnu/lib/MPI.a failed
```
So I assume that ElmerGUI is looking for MPI in `/usr` and not `/app` 

My flatpak manifest.
https://github.com/kevinsmia1939/flathub/tree/fi.csc.Elmer

**Comment by mmuetzel** [comment] 2024-08-28 12:57
`MPI::MPI_C` is the name of the imported CMake target that should contain all the information that is needed to build and link a C program with MPI. If that target doesn't exist, CMake assumes that it is the name of a library. Hence, you are seeing the flag `-lMPI::MPI_C`.

When it comes to why `MPI::MPI_C` doesn't exist for you: It might be that you built Open MPI without support for the C language. That might be the reason why CMake couldn't set up a target for it.
Or your CMake version is too old. You'll need a version of CMake that is at least 3.10 or newer.

Given that the issue is already almost 3 years old, I don't know if it is still an issue.
Should this report just be closed?

**Comment by kevinsmia1939** [comment] 2024-08-28 14:01
@mmuetzel 
Another issue was also reported on FreeBSD.
https://github.com/ElmerCSC/elmerfem/issues/334

But I will try again.

**Comment by raback** [comment] 2024-08-29 12:12
I am closing some old build related issues since most likely they are not relevant any more.

**Closed as completed by raback** 2024-08-29 12:12 UTC
